#ifndef TERMINAL_H
#define TERMINAL_H

#define TERMINAL_PORT_TX GPIOA
#define TERMINAL_PIN_TX GPIO2
#define TERMINAL_AF_TX GPIO_AF7

#define TERMINAL_PORT_RX GPIOA
#define TERMINAL_PIN_RX GPIO3
#define TERMINAL_AF_RX GPIO_AF7

#define TERMINAL_ESC "\033"
#define TERMINAL_CSI TERMINAL_ESC "["

#define TERMINAL_CSI_CUB(N) TERMINAL_CSI #N "D"
#define TERMINAL_CSI_CUF(N) TERMINAL_CSI #N "C"
#define TERMINAL_CSI_CCU(N) TERMINAL_CSI #N "A"
#define TERMINAL_CSI_CUD(N) TERMINAL_CSI #N "B"

#define TERMINAL_CSI_INSERT TERMINAL_CSI "2~"
#define TERMINAL_CSI_DELETE TERMINAL_CSI "3~"
#define TERMINAL_CSI_END TERMINAL_CSI "4~"
#define TERMINAL_CSI_PGUP TERMINAL_CSI "5~"
#define TERMINAL_CSI_PGDN TERMINAL_CSI "6~"
#define TERMINAL_CSI_HOME TERMINAL_CSI "7~"

#define TERMINAL_BUFFER_SIZE 32

#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T

#include <printf/printf.h>

void terminal_init(void);

#endif